# Generated by Django 5.1.7 on 2025-03-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
    ]
