# Generated by Django 5.1.7 on 2025-03-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_peca_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="JwtAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Jwt Token",
                "verbose_name_plural": "Jwt Tokens",
            },
        ),
    ]
